---
service: token
runtime: go
api_version: go1

handlers:
- url: /token(/.*)?
  script: _go_app

- url: /charge
  script: _go_app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /*
  static_dir: static